version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-dependencies-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: node-dependencies-{{ checksum "package.json" }}

  lint:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-dependencies-{{ checksum "package.json" }}
      - run: npm run lint

  test:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-dependencies-{{ checksum "package.json" }}
      - run: npm run cover-ci

workflows:
  version: 2
  build-lint-test:
    jobs:
      - build
      - lint:
          requires:
            - build
      - test:
          requires:
            - build
